#!/usr/bin/env bash

ls -la

echo GITHUB_ACTION=$GITHUB_ACTION
echo GITHUB_ACTOR=$GITHUB_ACTOR
echo GITHUB_REPOSITORY=$GITHUB_REPOSITORY
echo GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME
echo GITHUB_SHA=$GITHUB_SHA
