[build]
    publish = "out/"
    functions = "functions/"

[[redirects]]
    from = "https://turaosvenyek.netlify.app/*"
    to = "https://turaosvenyek.hu/:splat"
    force = true

[dev]
    publish = "_site/"
