name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build
      run: make
      env:
        ANALYTICS_ENABLED: ${{ secrets.ANALYTICS_ENABLED }}
        FATHOM_SITE_ID: ${{ secrets.FATHOM_SITE_ID }}
        MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        SERVER_PREFIX: ${{ secrets.SERVER_PREFIX }}

    - name: Verify
      run: make verify

    - name: Deploy
      run: ./deploy.sh
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
