name: Build and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: UseRuby 2.6.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build
      run: make
      env:
        ANALYTICS_ENABLED: ${{ secrets.ANALYTICS_ENABLED }}
        FATHOM_SITE_ID: ${{ secrets.FATHOM_SITE_ID }}
        MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
        SERVER_PREFIX: ${{ secrets.SERVER_PREFIX }}

    - name: Test
      run: make test
