name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Parse node version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: yarn
      - name: Build
        run: make
      - name: Create deployment
        run: make .tmp/deploy.tgz
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: .tmp/deploy.tgz
      - name: Write deployment file url
        uses: sergeysova/jq-action@v2
        env:
          WORKFLOW_RUN_ID: ${{ github.run_id }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: make .current-deployment-url.txt && cat .current-deployment-url.txt
