name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_RUN_ID: ${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Parse node version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: yarn
#      - name: Build
#        run: make
      - name: Create deployment
        run: make .tmp/deploy.tgz
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy
          path: .tmp/deploy.tgz
      - name: Store workflow run id
        run: make .workflow-run-id
      - run: |
          git checkout --orphan deploy
          git add .
          git commit -m "Deployment for workflow $(WORKFLOW_RUN_ID)"
          git pish origin deploy --force
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - run: echo $WORKFLOW_RUN_ID
#        env:
#          WORKFLOW_RUN_ID: ${{ github.run_id }}
#      - run: make .tmp/artifact-data.json
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#      - run: cat .tmp/artifact-data.json
#      - name: Write deployment file url
#        env:
#          WORKFLOW_RUN_ID: ${{ github.run_id }}
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#        run: make .current-deployment-url.txt ; cat .current-deployment-url.txt
